### ISSUE TITLE
Compatibility with .tif/.tiff files

### ISSUE THREAD

**Issue by BossensM** [MikeKovarik/exifr#2] opened 2019-06-08 11:39 UTC
Really nice and clean written library, best exif parse I've found so far! Works awesome with .jpg images. 

But when trying to parse a .tif file, no error is thrown and the result from the parsing is 'undefined'. 
Is the parser not compatible with tif files?

**Comment by MikeKovarik** [comment] 2019-06-08 14:27
Hello. Thanks for the compliments, glad you use it.

As far as I know EXIF structure in jpegs is built upon TIFF so I expected it to work, but didn't have enough time to test it properly. Not because I'd be reckless but because of the limited time I could dedicate to the library. So far I only used it for jpegs but if you could provide me with some tiffs to develop against, I may be able to look into it.

**Comment by BossensM** [comment] 2019-06-08 17:25
Please find attached two sample tif images. 
[Sample Tif.zip](https://github.com/MikeKovarik/exifr/files/3268772/Sample.Tif.zip)

I did some debugging myself and it seems like it fails finding the app segment (function findAppSegment). Would be great if you could look into this or provide some tips

**Comment by MikeKovarik** [comment] 2019-06-10 14:44
Hello. Yes, by taking a quick look i can say it's not able ti find the segment. Though it looks like all of the data is in the XMP (XML) format which this plugin does not parse by default anyway. 3rd party XML parser would be required for his anyway.

I'm not sure what to do about the tiff format yet. I'll look into it more if i have time

![image](https://user-images.githubusercontent.com/3995401/59203443-e4216c00-8b9e-11e9-927f-b6106ce5e75f.png)

**Comment by BossensM** [comment] 2019-06-10 14:52
There is indeed XMP data but there should also be some EXIF data. If you eg use http://exif.regex.info/exif.cgi you can see what the contents of the Exif are.

**Comment by MikeKovarik** [comment] 2019-06-10 15:00
You're right. The TIFF segment is at the very beginning of the file, whereas the jpg exif always starts with other data. The module is ready for this. There's a `parseTiff()` method on the `ExifParser` class.
![image](https://user-images.githubusercontent.com/3995401/59204551-2c418e00-8ba1-11e9-8e01-4e98a204cb83.png)

**Comment by BossensM** [comment] 2019-06-10 15:08
It seems the parseTiff function would be able to handle it, but it fails at the beginning ensureSegmentPosition because it does not find the app segment?

**Comment by MikeKovarik** [comment] 2019-06-10 15:19
Yes. I'm trying to recall the segments, byte orders, etc.. so it takes a while for me to look around the almost a year old code :D.
There's a `findTiff` function called both in `parseTiff` method like you say, but also in index.mjs where it gets you the `exifPosition` (`var exifPosition = findTiff(view)`) and it fails because the `49 49` is not wrapped in an app segment. As far as my memory reaches i don't think we need the segment info (its there to give us the size of the segment) so we may be able to return 0 from `parseTiff` and feed the tiff position to https://github.com/MikeKovarik/exifr/blob/master/src/parser.mjs#L167

**Comment by BossensM** [comment] 2019-06-10 15:22
I got it to work ! If `if (exifPosition)` is null,  just provide `{start: 0}` as tiffPostion to the constructor makes it all work.

**Comment by MikeKovarik** [comment] 2019-06-10 15:31
Yes, but that's a dirty trick. This module tries to be as fast as possible. So when there's no indication of exif data it stops. Assuming it's always 0 when nothing is found would end up reading and parsing whole file which might not have any exif at all :D. I'll have to come up with a little more elegant solution.

**Comment by BossensM** [comment] 2019-06-10 15:33
Yes agree it's not a clean fix. Maybe instead of looking for the app segment, you could directly look for the marker? It expects these two cases anyway or it throws:

`if (marker === 0x4949)
			this.le = true // little endian
		else if (marker === 0x4D4D)
			this.le = false // big endian`

**Comment by BossensM** [comment] 2019-06-10 15:46
I did some extra testing and found another issue. The .tif file works great and has all exif data, but the .tiff image misses some data like the GPS information. It seems like both GPSInfoIFDPointer and ExifIFDPointer are null in the parseTiff method. Any idea what is going wrong there?

**Comment by MikeKovarik** [comment] 2019-06-10 15:49
I haven't gotten there yet (no that i would be aware of it). I'm trying to polish the first problem now. It'd be great if you could dig into it more for now.

**Comment by MikeKovarik** [comment] 2019-06-10 16:11
Got it to work. Greetings to Leuven :D.
I'll finish this up when i get home.

**Comment by BossensM** [comment] 2019-06-10 16:12
The GPS issue or the app segment issue ? :D

**Comment by MikeKovarik** [comment] 2019-06-10 16:13
Read my last message again :D

**Comment by BossensM** [comment] 2019-06-10 16:25
For the issue of reading GPS data, I debugged in until the point where it tries to parse the value. It find the GPSInfoIFDPointer key, but the problem is the type of the value is "13" which is not part of the switch case, hence returning undefined https://github.com/MikeKovarik/exifr/blob/bd00a145fa5734a68636f662c51e12a42e8f5b8c/src/parser.mjs#L331

Trying to understand what this switch does

**Comment by BossensM** [comment] 2019-06-10 16:31
Actually the issue is already higher up where the SIZE_LOOKUP does not contain more than 10 entries https://github.com/MikeKovarik/exifr/blob/bd00a145fa5734a68636f662c51e12a42e8f5b8c/src/parser.mjs#L297

**Comment by BossensM** [comment] 2019-06-10 16:54
I dont really understand what is going on. In the EXIF standard only 10 types exists, so don't understand how we can get a type 13 here.

**Comment by BossensM** [comment] 2019-06-10 17:10
I fixed it, again dirty: if type is 13, Im mapping it back to 4 which is a LONG (according to the EXIF specs, this is what GPSInfoIFDPointer should be);

**Comment by MikeKovarik** [comment] 2019-06-10 20:21
I finally got home and finished polishing the first problem. Though i haven't run into the second. I successfuly extracted the GPS info from the .tif file on the first go and discovered that they're from the city Leuven. That's what i meant by the previous messages.

Anyway. I pushed version that works now. it works in node, not in browser because of the way we load files in browser. we just load the first few kb of the file, but this .tif has some data at the end of the file too. I'm thinking of rewriting the parsers anyway because it's quite messy.

could you try it out if your GPSInfoIFDPointer persists or is solved by my code?

**Comment by BossensM** [comment] 2019-06-10 20:37
Thanks, will have a try. Don't understand why it wouldn't work in the browser though. My 'dirty fix' worked perfectly in the browser (using ArrayBuffer).

With regards to the GPS issue, see my comment above what fixes it, but don't know what the real cause is. Maybe TIFF files have extra types?

**Comment by MikeKovarik** [comment] 2019-06-11 08:20
To clarify the browser issue. It works in browser if you feed the whole image ArrayBuffer into the library. But the tests are written to feed it url which then loads it in chunks instead of downloading the whole file. That's the problem.

Last thing last night i did was add a few tests, try running them both in browser and mocha and you'll see.

I should:
1. rewrite & add more tests to test both reading modes (read whole file, read file by chunks)
2. fix the chunked reading (works in node, not in browser, well it works)

**Comment by MikeKovarik** [comment] 2019-06-17 14:24
status update: I've been silently rewriting big portion of the library over the past week.

- Improving the tiff support
- rewriting tests
- rewrote file reading from functions to classes
- added extraction of thumbnail buffer

That would be 2.0.0.

If ill have enough time i'll also rewrite the chunked reading. Not that it's not working. It does on simple images where all metadata are stacked together. The library reads only the first 64kb (`parseChunkSize`) of any file when in chunked reading mode (both can be customized in options). The file you provided interestingly has some metadata offseted outside the 64kb. So either the chunk size has to be increased or the library has to be able to read more chunks. That's tricky in the way it's currently written. Now that I know about this I'd like to implement it, though I'll save it for 3.0.0.

**Comment by MikeKovarik** [comment] 2019-06-17 14:29
@BossensM have you tried the code since we discussed it? Like I said, I believe the unknown type 13 was caused by some incorrect offset caused by the dirty tricks. Have you tried / could you try the current code?
FYI: In the coming days i'll push even more changes, mostly breaking changes. I'd appreciate feedback before the 2.0.0 is released.

**Comment by BossensM** [comment] 2019-06-17 14:47
I have tried the latest master, but still same issues with the .tiff file. As said earlier the .tif works, it's only the .tiff (which is coming from another type of camera) that has issues reading the GPS info. 

Nice working on improving the library !

**Comment by MikeKovarik** [comment] 2019-06-17 15:59
OOoooh. Now i get it. I assumed both of your files are from the same camera and only added 001.tif to tests and forgot about the 002.tiff.

So 001.tif works nicely and 001 i'll have to look into tomorrow.

**Comment by MikeKovarik** [comment] 2019-06-18 07:48
You were right with the type 13 and it's not such a dirty fix you did afterall :D. Here's more info about it. https://sno.phy.queensu.ca/~phil/exiftool/standards.html

**Comment by BossensM** [comment] 2019-06-18 11:13
Interesting ! Didn't see that page. Will you also implement a fix in that for v2.0 ?

**Comment by MikeKovarik** [comment] 2019-06-18 11:17
Yes. Already fixed with tests. I'll push it tonight

**Comment by GeoffreyBooth** [comment] 2019-07-01 23:42
Would you mind publishing a new version to NPM?

**Comment by MikeKovarik** [comment] 2019-07-02 06:36
Yes. I'm planning to, but I've been trying to squeeze new docs and examples into 2.0 as well. It took a little longer due to crunch around release in my day job.

I'll try to publish it tonight (European time).
Thanks for interest.

**Comment by MikeKovarik** [comment] 2019-07-05 18:21
@BossensM @GeoffreyBooth It's done. Just released 2.0.0. I'm sorry it took a little longer. I kept finding bugs, unexpected outputs, fixing stability, adding tests and making sure it's stable.

If you're interested in future of the library, there is a little roadmap at the bottom of a readme.

**Closed by MikeKovarik** 2019-07-05 18:21 UTC

**Comment by BossensM** [comment] 2019-07-10 12:51
Nice work Mike !
